services:
  ollama:
    image: ollama/ollama:latest
    stdin_open: true
    tty: true
    container_name: ${COMPOSE_PROJECT_NAME}-ollama
    environment:
      - TZ=${TIMEZONE}
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ${DATA_ROOT}/ollama:/root/.ollama
    ports:
      - "127.0.0.1:11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: ${COMPOSE_PROJECT_NAME}-openwebui
    depends_on:
      - ollama
    environment:
      - TZ=${TIMEZONE}
      - OLLAMA_BASE_URL=http://ollama:11434
      - SEARCH_PROVIDER_URL=http://searxng:8080
      - SEARCH_ENABLED=true
    volumes:
      - ${DATA_ROOT}/openwebui:/app/backend/data
    ports:
      - "${OPENWEBUI_PORT}:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    container_name: ${COMPOSE_PROJECT_NAME}-searxng
    environment:
      - TZ=${TIMEZONE}
      - BASE_URL=http://localhost:8081
      - SEARXNG_SECRET=${SEARXNG_SECRET:-changeme}
      - BIND_ADDRESS=0.0.0.0
      - PORT=8080
      - LIMITER=false
    volumes:
      - ${DATA_ROOT}/searxng:/etc/searxng
    ports:
      - "127.0.0.1:8081:8080"
    restart: unless-stopped
