services:
  sim:
    image: ghcr.io/simstudioai/sim:latest
    container_name: ${COMPOSE_PROJECT_NAME}-sim
    environment:
      - TZ=${TIMEZONE}
      - PORT=3000
      - NEXT_PUBLIC_APP_URL=${SIM_PUBLIC_URL}
      - BETTER_AUTH_URL=${SIM_PUBLIC_URL}
      - BETTER_AUTH_SECRET=${SIM_AUTH_SECRET}
      # Optional: local model endpoint if you run Ollama
      - OLLAMA_BASE_URL=http://ollama:11434
      # Disable DB features entirely
      - DISABLE_DATABASE=true
    volumes:
      - ${DATA_ROOT}/sim/uploads:/app/.data/uploads
      - ${DATA_ROOT}/sim/config:/app/.data/config
    ports:
      - "${SIM_PORT:-3000}:3000"
    restart: unless-stopped

  realtime:
    image: ghcr.io/simstudioai/realtime:latest
    container_name: ${COMPOSE_PROJECT_NAME}-sim-realtime
    environment:
      - TZ=${TIMEZONE}
      - PORT=3010
      # Run realtime standalone (no DB)
      - DISABLE_DATABASE=true
    ports:
      - "${SIM_REALTIME_PORT:-3010}:3010"
    restart: unless-stopped
networks:
  homelab:
    name: homelab
    external: true
